### ISSUE TITLE
Is this going to move the screen recorder from Video For Windows codecs?

### ISSUE THREAD

**Issue by PicelBoi** [LazyDuchess/OpenTS2#10]
VFW is still being used, and honestly would this ruin my video recorder settings? I spent some time getting TS2 to output videos via x264vfw and hearing that this reimplements TS2 makes me wonder if this would modernize TS2 as a whole. Will this reimplementation remove the screen recorder or at least change it so it does not use something that was a reaction to Apple's QuickTime?

**Comment by LazyDuchess** [comment]
It's a complete rewrite so when and if we manage to get to screen recording we'll see what we end up doing, the codec will definitely be different.
