### ISSUE TITLE
Best Way to Contact?

### ISSUE THREAD

**Issue by berylliumquestion** [LazyDuchess/OpenTS2#12]
I was wondering the best way for aspiring contributors to communicate with you? I know issues are one way, but I was wanting to maybe talk in a more conversational style to see what your current goals are, because, and it's a bit embarrassing for me to say, I'm just a bit lost as to how I might able to contribute to this project.

**Comment by LazyDuchess** [comment]
Hi! You can message me on discord: Lazy Duchess#1640 or hit me up on twitter if you don't have that.
