### ISSUE TITLE
Improve support for the STR format

### ISSUE THREAD

**Issue by lingeringwillx** [LazyDuchess/OpenTS2#19]
There are a few rare STR formats that could be found in the game's files, but I haven't seen anyone mention them anywhere. I pulled all of these from the objects.package:

**1- STR Format: Zero**

Spec:
Name: 64 bytes
Null/Format Code?: 2 bytes

<details>
<summary>Resources</summary>

endtable1 skill table
Type: 0x53545223, Group: 0x7FAB08F6, Instance: 0x00000081, Resource: 0x00000000

Nightstand Expensive skill table
Type: 0x53545223, Group: 0x7F280D6D, Instance: 0x00000081, Resource: 0x00000000

bedstandex attribute labels
Type: 0x53545223, Group: 0x7F280D6D, Instance: 0x00000100, Resource: 0x00000000
</details>

**2- STR Format: No Format**

Spec:
Name: 64 bytes
Null/Format Code?: 1 byte integer
Count: 1 byte integer

Loop _Count_ times:
Length: 1 byte integer
Value: String with length _Length_
	
<details>
<summary>Resources</summary>

Behavior editor string set
Type: 0x53545223, Group: 0x7F6D880B, Instance: 0x0000012C, Resource: 0x00000000

Behavior editor string set
Type: 0x53545223, Group: 0x7FBD8997, Instance: 0x0000012C, Resource: 0x00000000
</details>

**3- STR Format: 0xFFF6**
This is a weird format with some weird dividers between the strings, even SimPE won't read it, and I couldn't figure it out the last time I tried. Here is the resources with this format if anyone wants to try to figure them out:

<details>
<summary>Resources</summary>

Suit primitive strings
Type: 0x53545223, Group: 0x7F3D258A, Instance: 0x00000130, Resource: 0x00000000

Suit primitive strings
Type: 0x53545223, Group: 0x7FE94D58, Instance: 0x00000130, Resource: 0x00000000

Suit primitive strings
Type: 0x53545223, Group: 0x7F27193D, Instance: 0x00000130, Resource: 0x00000000

Suit primitive strings
Type: 0x53545223, Group: 0x7F24F935, Instance: 0x00000130, Resource: 0x00000000

Suit primitive strings
Type: 0x53545223, Group: 0x7F83D9EC, Instance: 0x00000130, Resource: 0x00000000

Suit primitive strings
Type: 0x53545223, Group: 0x7F2CAB90, Instance: 0x00000130, Resource: 0x00000000

Suit primitive strings
Type: 0x53545223, Group: 0x7FBEBDFE, Instance: 0x00000130, Resource: 0x00000000

Suit primitive strings
Type: 0x53545223, Group: 0x7FFAA5E5, Instance: 0x00000130, Resource: 0x00000000

Suit primitive strings
Type: 0x53545223, Group: 0x7F234024, Instance: 0x00000130, Resource: 0x00000000
</details>

**4- STR Format: 0xFFFD**
Already known.

**5- STR Format: 0xFFFE**

Spec:
Name: 64 bits
Format Code: 2 bytes integer
Count: 2 bytes integer

Loop _Count_ Times:
Value: Null-terminated String
Null: 1 byte (Description string?)

<details>
<summary>Resources</summary>

Relationships
Type: 0x53545223, Group: 0x7F6D880B, Instance: 0x00000102, Resource: 0x00000000

relationship labels
Type: 0x53545223, Group: 0x7F17187C, Instance: 0x00000102, Resource: 0x00000000

PedPortal relationship labels
Type: 0x53545223, Group: 0x7F19EC55, Instance: 0x00000102, Resource: 0x00000000

Mail Box relationship labels
Type: 0x53545223, Group: 0x7FE4B434, Instance: 0x00000102, Resource: 0x00000000

Relationships
Type: 0x53545223, Group: 0x7FBD8997, Instance: 0x00000102, Resource: 0x00000000

Suit primitive strings
Type: 0x53545223, Group: 0x7F979D47, Instance: 0x00000130, Resource: 0x00000000

Suit primitive strings
Type: 0x53545223, Group: 0x7FE9B3DE, Instance: 0x00000130, Resource: 0x00000000

Suit primitive strings
Type: 0x53545223, Group: 0x7F8ECBFD, Instance: 0x00000130, Resource: 0x00000000

Suit primitive strings
Type: 0x53545223, Group: 0x7F79C748, Instance: 0x00000130, Resource: 0x00000000

Suit primitive strings
Type: 0x53545223, Group: 0x7F1FF01F, Instance: 0x00000130, Resource: 0x00000000

Suit primitive strings
Type: 0x53545223, Group: 0x7F9E24A1, Instance: 0x00000130, Resource: 0x00000000

Suit primitive strings
Type: 0x53545223, Group: 0x7FFCB26D, Instance: 0x00000130, Resource: 0x00000000

Suit primitive strings
Type: 0x53545223, Group: 0x7F1E9307, Instance: 0x00000130, Resource: 0x00000000

Suit primitive strings
Type: 0x53545223, Group: 0x7F694047, Instance: 0x00000130, Resource: 0x00000000

named trees
Type: 0x53545223, Group: 0x7F979D47, Instance: 0x00001000, Resource: 0x00000000

named trees
Type: 0x53545223, Group: 0x7FE9B3DE, Instance: 0x00001000, Resource: 0x00000000

named trees
Type: 0x53545223, Group: 0x7F8ECBFD, Instance: 0x00001000, Resource: 0x00000000

named trees
Type: 0x53545223, Group: 0x7F79C748, Instance: 0x00001000, Resource: 0x00000000

named trees
Type: 0x53545223, Group: 0x7F1FF01F, Instance: 0x00001000, Resource: 0x00000000

named trees
Type: 0x53545223, Group: 0x7F9E24A1, Instance: 0x00001000, Resource: 0x00000000

named trees
Type: 0x53545223, Group: 0x7FFCB26D, Instance: 0x00001000, Resource: 0x00000000

named trees
Type: 0x53545223, Group: 0x7F1E9307, Instance: 0x00001000, Resource: 0x00000000

named trees
Type: 0x53545223, Group: 0x7F694047, Instance: 0x00001000, Resource: 0x00000000

skin colors
Type: 0x53545223, Group: 0x7F01EC29, Instance: 0x00002000, Resource: 0x00000000
</details>

**6- STR Format: 0xFFFF**
This is the same as format 0xFFFD, but STR entries that have this format are always empty/have no strings.

Spec:
Name: 64 bytes
Format Code: 2 bytes integer
Count: 2 bytes integer

**Comment by LazyDuchess** [comment]
Interesting, thanks for letting me know. I'm assuming at least most of these have gone unused in the actual game, as they seem to reference TS1 things like suit primitives.

**Comment by lingeringwillx** [comment]
> Interesting, thanks for letting me know. I'm assuming at least most of these have gone unused in the actual game, as they seem to reference TS1 things like suit primitives.

They could be, but I'd have to check.

**Comment by lingeringwillx** [comment]
Closing this issue. It's available for reference if anyone needs it.
