### ISSUE TITLE
Figure out SPX (Speech) Audio format

### ISSUE THREAD

**Issue by LazyDuchess** [LazyDuchess/OpenTS2#2]
I have no experience figuring out audio formats, so this is something I will need help with.
In the TSData/Res/Sound folder there are Voice1, Voice2, etc. packages. Inside of them there are audio files that begin with a SPX1 magic number - these are the audio files left to figure out.

**Comment by ammaraskar** [comment]
Aah these look to be Speex https://www.speex.org/ files with a custom header instead of vorbis? Haven't tried decoding them yet but it looks like from the symbol names they use this official speex library in the game: https://www.speex.org/docs/api/speex-api-reference/globals.html

Notice the symbols like `speex_wb_mode`, `speex_bits_init` etc

**Comment by LazyDuchess** [comment]
Haven't touched this yet, I believe there is Speex source code floating around if you want to take a look, but it's all C/C++ as far as I know. Also just a really obscure format nowadays.

**Comment by actioninja** [comment]
Been picking at this one. I have a start but it's still pretty gnarly. Getting a rough idea of what the header looks like but basically every field I'm like "maybe this?"
It looks like it's roughly:
4 byte magic number,
1 byte flag,
4 bytes padding(?),
4 bytes either speex mode when flag is 0 or unknown when flag is 1
2 bytes unknown

Unfortunately the main implementations are all some cpp nonsense so all the calls are behind vtables that I haven't worked out of the location of. Still getting a handle on how Ghidra works, and a plugin to resolve rtti wasn't working right.

The actual file seems to have the header followed by some kind of regular potentially padding data, then something that seems to be the actual speex payload. Once where the custom implementation falls out and it's just calling libspeex decode it should be fairly easy from there.

**Comment by LazyDuchess** [comment]
> Been picking at this one. I have a start but it's still pretty gnarly. Getting a rough idea of what the header looks like but basically every field I'm like "maybe this?" It looks like it's roughly: 4 byte magic number "1XPS", read as BE, 1 byte flag, 4 bytes padding(?), 4 bytes either speex mode when flag is 0 or unknown when flag is 1 2 bytes unknown
> 
> Unfortunately the main implementations are all some cpp nonsense so all the calls are behind vtables that I haven't worked out of the location of. Still getting a handle on how Ghidra works, and a plugin to resolve rtti wasn't working right. IDA was choking on it as well, giving binary ninja a shot.
> 
> The actual file seems to have the header followed by some kind of regular potentially padding data, then something that seems to be the actual speex payload. Once where the custom implementation falls out and it's just calling libspeex decode it should be fairly easy from there.

Hey! Thanks for checking this out, happy to see some progress.

I should probably link to this somewhere, maybe in the readme, there's a MAC build of the Bon Voyage executable with debug symbols which might help as it reveals function and class names: [Dropbox Link](https://www.dropbox.com/s/uyo4wtf5ck8cscg/%5BMAC%5D%20The%20Sims%202%20-%20Bon%20Voyage%20%5B2007-12-17%5D.7z?dl=0)

**Comment by actioninja** [comment]
Here's (approximately) what the header read code looks like:
```CXX
int __thiscall cGZSpeexCodec::ReadHeader(cGZSpeexCodec *this, cIGZIStream *buffer)
{
  bool pass;

  int magic;
  pass = buffer->GetUint32(&magic);
  // 0x31585053 = 31 58 50 53 = "1XPS" = "SPX1" in LE
  if (!pass || magic != 0x31585053) {
      return 0;
  }
  char flag;
  pass = buffer->GetUint8(&flag);
  //flag doesn't seem to actually affect control flow? Potentially optimized out dead branch here
  if (!pass || flag != 1) {
      return 0;
  }
  //this literally relates to a field behind a "GetSize" method.
  // doesn't seem to relate to decoding, not read at all internally
  // GetSize is only called behind a vtable so going to need some work to find out what this is actually used for
  pass = buffer->GetUint32(&this->size);
  if (!pass) {
      return 0;
  }
  // possible values here are:
  // 0: speex_nb_mode
  // 1: speex_wb_mode
  // 2: speex_uwb_mode
  pass = buffer->GetSint32(&this->speexmode);
  if (!pass) {
      return 0;
  }
  // in reality, the `vec_size_int` field on the cGZSpeexCodec class is u32,
  // so this happens in two phases; first read then set with a cast
  // unsure if this *is* a size hint, the vec calls are particularly mangled in disassembly.
  // this relates to some kind of internal buffer for decoding the speex frames
  pass = buffer->GetUint16(&this->vec_size_hint);
  if !(pass) {
      return 0;
  }
  return 1;
}
```
From this, here's the header:
- 4 bytes: Magic Number
- 1 byte: Some kind of flag, always 1? TS2 Prod code fails read if it's not 1
- 4 bytes: data size? Not actually used when decoding
- 2 bytes: frame buffer size hint?

Following these 11 bytes seems to be the actual speex frames. Going to work on picking at the vtables and see if I can figure out at what point it just calls out to libspeex.

**Comment by actioninja** [comment]
so turns out these *aren't* speex frames, they're some kind of further encoded audio frames that do some kind of nonsense before actually calling the speex frame decode. Fun.

Seems like it *might* just be 1 byte frame size followed by the speex frame? not sure.

**Comment by actioninja** [comment]
Tentatively saying I think I've got it, working on writing a tool to decode spx1 files to wav now. If that works, then this is correct, and the true test of it actually being accurate will be reencoding

header:
    4 bytes: Magic Number (SPX1 in Little Endian)
    1 byte: Always 1
    4 bytes: data size of unencoded data, not actually used for decoding seems to be some kind of reference number similar to other s2 datatypes
    2 bytes: largest speex frame, helps prevent reallocations when decoding because the same buffer is reused

payload:
arbitrary number
1 byte: frame size in bytes
(number of bytes specified by first bytes): speex frame, can be directly decoded with libspeex

**Comment by LazyDuchess** [comment]
awesome, should be straightforward to turn into unity audioclips if the wav conversion works

**Comment by lingeringwillx** [comment]
There is now a new library that comes with a precompiled speex library dll and C# bindings: https://github.com/SlimeNull/SpeexSharp

I tested @actioninja's specification and I'm getting working sound files from it, albeit I did it in python: https://github.com/lingeringwillx/ts2-speex

It's just that the size written in the file ends up being different than that the actual decoded file size, so I don't know if there is any small mistakes there.

**Comment by lingeringwillx** [comment]
The format suggested by @actioninja is roughly correct:

```
4 bytes: magic header (SPX1)
1 byte: number of channels (always 1, mono)
4 bytes: decoded size
4 bytes: speex mode (always 2, ultra-wideband mode, sampling rate 32khz)
2 bytes: samples per frame/decoded frame size (640 samples, or 1280 bytes)

loop until the end of the file:
1 bytes: encoded frame size
encoded speex frame
```

You would call speex_decode_int on the encoded frames to decode the file, the decoded frame size is always 640 samples/1280 bytes.

The total decoded file size actually comes out to be a little larger than the decoded size written in the header. This is likely because zeros were appended to the end of the file before encoding so the last frame would have the same size as the other frames. To work around this you could just allocate your array/buffer to the decoded size from the header + 1280 bytes, so that you won't need to resize the array later.

I've [managed](https://github.com/lingeringwillx/ts2-speex) to decode the files using this format.

I found two C# libraries that can decode speex:
[NSpeex:](https://github.com/aijingsun6/NSpeex) Pure C# library, It appears to be used as a dependency in one popular [library](https://github.com/naudio/NAudio). The [issue](https://github.com/aijingsun6/NSpeex/issues/1) posted in the repository might also be relevant as it claims that it has fixed a problem with the library.  
[SpeexSharp:](https://github.com/SlimeNull/SpeexSharp) C bindings to the original speex library.

**Comment by LazyDuchess** [comment]
That works great! Might implement NAudio as it's convenient for playing MP3s as well. Thank you!

**Comment by LazyDuchess** [comment]
Implemented, works like a charm!
