### ISSUE TITLE
Garbled text in xml in some dbpf files

### ISSUE THREAD

**Issue by berylliumquestion** [LazyDuchess/OpenTS2#20]
I think there are xml files in package files because of the presence of xml tags, however trying to understand it is a bit of challenge because of all this garbage in it. I thought maybe it might be compressed, but then if it were I shouldn't be able to tell it's xml at all. It reminds me of lua files extracted from hpks dlc in Tropico 4, but I don't think you can compile xml?

Here's an example of what I'm talking about:
`!��û�ê<?xml version="1.0"?>`

`<cGZPropertySetString&#7"ä`
`    <!--editor paramet� --çAnyUint32 key="id" type="0xeb61eE4fâ0x718c6e9a</0?v?àfoldCerã0b8bea18">`

`EP4Rel™atàship	Is:‘�IánodeText�Kæ10 Simultaneous Pet Best FriŽÀ[end éprimaryIcon: used in UI when there is a 4sl�'à sho“)wn‡�O’2áfeedcf202�Œ6se›@ŽdaŠtwoás, e.g.,£ if ðžs�¯�)‰ '“�¬‰�o’�®�0�®A4GBB E ¼á Flag toFG d#+min	‡fàWant$2áuld be lÖoad
by(¯Aƒa“�¡bgM¸V@¤s‘K64(ç@þ!:á15 bit GvUIDàat p-o '%ÚoL^A-sáresource”A0.T�‡ŽÁ&515`

`‹¾ácheckTreB¿e’ƒ; /@0•€5baá>`

`CT - HaBžnd+FœEásimArrayª�‰àleve@‚làPowe‘@srˆ;ˆÀlcoràc264c¶712U_2.‘�=áinfluenc‘�AŽ�=@�àNodeƒE ˆ„Ùieˆ�ÓàobjeRctT�ØàNoneœK�uàeger­�B‰�ÜBáMultipli‰)`

`<&‘"Ž�ˆðOdQ¥�Œ +c¤Eve‘,àBoolbean@�àntRec)qui»câcba908e1"> Fadls:’�Jádeprecat‡FZeš�D†× </ý>+`

**Comment by LazyDuchess** [comment]
Are you using SimPE to open packages? The game does use XMLs quite a bit, yes, and resources are often compressed, though both SimPE and OpenTS2 should be able to load and decompress them correctly.

**Comment by LazyDuchess** [comment]
What's the file this resource is in, and its key? (instance id, group id, etc.)

You can find the DBPF compression and decompression code here: [DBPFCompression.cs](https://github.com/LazyDuchess/OpenTS2/blob/master/Assets/Scripts/OpenTS2/Files/Formats/DBPF/DBPFCompression.cs), and on the Sims Wiki [here](https://modthesims.info/wiki.php?title=DBPF_Compression).
It doesn't make files completely unreadable, you can kinda make out what they're about. It looks like the first few bytes might be the header of the compression?
