### ISSUE TITLE
Figure out JFIF/JPEG ALFA blocks.

### ISSUE THREAD

**Issue by LazyDuchess** [LazyDuchess/OpenTS2#4]
The game generates thumbnails as JPEG images, and embeds a custom ALFA block in them to achieve transparency:

![alfablock](https://user-images.githubusercontent.com/42678262/197315539-fc7ce7b9-7f72-43fa-aad6-181736b9787f.png)

The image above is a Sim thumbnail opened with a HEX editor. They don't look terribly complicated to figure out, they're Run Length Encoded.

**Comment by LazyDuchess** [comment]
For the time being I'll be doing color picking and some other prost processing to get rid of the black bg. Obvs not ideal but will do for now.
![image](https://user-images.githubusercontent.com/42678262/197896497-1f8f0273-7859-4d9f-85d1-196358855c60.png)

**Comment by ammaraskar** [comment]
Got it :)

### Raw

![image](https://user-images.githubusercontent.com/773529/205239331-d8408030-f732-42e2-8d29-5a48f1909da3.png) 

### Transparency Mask

![image](https://user-images.githubusercontent.com/773529/205239356-6b234ad9-c75a-41e7-b794-6ae731aefda2.png)

## Details

<details>
  <summary>Python Parsing Code</summary>

```python
def setTransparencyFromALFA(im, alfa):
    im2 = im.convert('RGBA').copy()
    transparency = []
    
    i = 0
    while i < len(alfa):
        rle_byte = int.from_bytes(alfa[i:i+1], byteorder='big', signed=True)
        
        i += 1
        if rle_byte < 0:
            # Repeat the next transparency n times.
            t = alfa[i]
            transparency.extend([t] * ((-rle_byte) + 1))
            i += 1
        else:
            # Read n unique transparency values.
            for _ in range(rle_byte + 1):
                transparency.append(alfa[i])                
                i += 1
                
    print(len(transparency))
    ctr = 0
    for j in range(im.size[0]):
        for i in range(im.size[1]):
            pixel = im2.getpixel((i, j))
            pixel = (transparency[ctr], pixel[1], pixel[2], pixel[3])
            ctr += 1
            im2.putpixel((i, j), pixel)
            
    return im2
```
</details>


It uses a similar RLE scheme to the `.reia` files:

* Read a single signed byte `n`.
* If `n` is negative:
  - Repeat the next byte `(-n) + 1` times.
* If `n` is positive:
  - Read `n + 1` unique bytes.
* The bytes read give the transparency channel values.

Let me see if I can send a pull request to add this to `IMGCodec.cs` to get familiarized with the codebase.

**Comment by LazyDuchess** [comment]
Awesome!
Cool that you figured out the RLE - I did notice there was some different behavior depending on if the byte was positive or negative but I hadn't thought of this.
