### ISSUE TITLE
Pick correct road textures

### ISSUE THREAD

**Issue by ammaraskar** [LazyDuchess/OpenTS2#45]
Currently we just use `new_roads_` as the road texture prefix. This actually varies between neighborhood, not sure where it's stored.

**Comment by LazyDuchess** [comment]
These might be hardcoded? Or defined in the install files.

Terrain type is stored in two places in the nhood packages as strings "Temperate, Desert, etc."

In the NGBH resource (type 0x4E474248) - here it dictates what terrain type the roads are, both in hood view and lot skirt.
In the Terrain Geometry resource (type 0xABCB5DA4) - this is the actual terrain type that will be displayed on the terrain.

So changing the terrain in the ngbh will only change the roads and vice versa.

**Comment by LazyDuchess** [comment]
I've implemented road texture names for the terrain types
![image](https://github.com/LazyDuchess/OpenTS2/assets/42678262/eb7fb5e2-459e-41fd-9d89-1388112776aa)
![image](https://github.com/LazyDuchess/OpenTS2/assets/42678262/ef650121-5593-4b4f-aee8-141685f74f0e)

**Comment by ammaraskar** [comment]
Woo <3
