### ISSUE TITLE
Create shaders for different terrain types

### ISSUE THREAD

**Issue by LazyDuchess** [LazyDuchess/OpenTS2#46]
Right now only Temperate and Concrete terrain types render accurately, The terrain paint for Desert and Dirt don't have the same behavior as them, which makes them look strange.

Might have to rework the terrain shader a little into a cginc to avoid redundant code.

**Comment by LazyDuchess** [comment]
There we go :)
![image](https://github.com/LazyDuchess/OpenTS2/assets/42678262/e25a38b6-5c83-43d5-850d-3f3688934bcb)
![image](https://github.com/LazyDuchess/OpenTS2/assets/42678262/33447f4b-e936-456f-9ce6-94a521edd4ae)

**Comment by ammaraskar** [comment]
Nice, this looks great.
