### ISSUE TITLE
Load and render lot walls and floors

### ISSUE THREAD

**Issue by ammaraskar** [LazyDuchess/OpenTS2#51]
Gotta figure out which files hold information about where walls and floors should go in a lot.

**Comment by polikarmike** [comment]
Hello! As far as I understand, information about walls, fences, pools, etc. is stored in a file of type WGRA(0A284D0B), which refers us to a file of type WLL(WLAY in Simpe)(8A84D7B0), which contains information about the front and back sides of the wall, while the texture itself is stored in a file of type SMAP(CAC4FC40).

More information about the structure and details here:
WGRA: https://simswiki.info/wiki.php?title=WGRA
WLL: https://simswiki.info/wiki.php?title=WLL
SMAP: https://simswiki.info/wiki.php?title=SMAP

The situation with floors is slightly more complex. As far as I understand, information about tiles is stored in the format 3ARY(2A51171B) under the Instance ID 0x00, and then it refers to a file of type SMAP(CAC4FC40),  where the floor texture itself is stored.

You can find more information about the structure and details here:
3ARY: https://simswiki.info/wiki.php?title=3ARY
SMAP: https://simswiki.info/wiki.php?title=SMAP

I hope that helped a little :)

**Comment by ammaraskar** [comment]
Thank you for the info, I think @riperiperi has most of it figured out in #52

**Comment by ammaraskar** [comment]
Fixed in #52
