### ISSUE TITLE
Fix DBPF Compression

### ISSUE THREAD

**Issue by LazyDuchess** [LazyDuchess/OpenTS2#54]
Compression/Decompression code is in Assets/Scripts/OpenTS2/Files/Formats/DBPF/DBPFCompression.cs

Decompression works perfect, but compression works for some things but not for others. STR# resources for example seem to compress ok most of the time, but neighborhood terrain geo throws an exception, so I think compression code should be rewritten to be able to handle all files.

As a workaround currently the CanBeCompressed property in AbstractAsset returns false, skipping compression. This is not a huge deal however as saving works just fine otherwise minus the compression.

**Comment by ammaraskar** [comment]
Some references: 

* https://github.com/sebamarynissen/sc4/blob/0439ec1d3a12c84af91b7d1e2f23ab3c8c257fc0/lib/dbpf.js#L19
* https://github.com/actioninja/refpack-rs

The second library links to http://wiki.niotso.org/RefPack as well.

**Comment by lingeringwillx** [comment]
I tried to replace the pattern matching code with my own and I'm getting the same problem with large files not compressing correctly. I think the problem might be in the encoding, specifically in the bigger range, but I stared at that for a while and I can't find any problem 😫.

**Comment by ammaraskar** [comment]
Oh I just realized the second library there is by @actioninja who helped out in #2. If you have some time, could you check at a glance what might be wrong with the compression code in https://github.com/LazyDuchess/OpenTS2/blob/master/Assets/Scripts/OpenTS2/Files/Formats/DBPF/DBPFCompression.cs?

**Comment by lingeringwillx** [comment]
My typical approach to spare the pain is to write bindings to C++/a DLL, but I don't know if that's something that you want to do.

There is the old code used by the Compressorizer which was published a long time ago in moreawsomethanyou, which I [managed](https://github.com/lingeringwillx/sims2lib/blob/main/dbpf.cpp) to adjust slightly to make it bindable to other languages.

A minor quip is that the code is GPL licensed so I guess you'd have to switch to that license as well.

I have my own C++ code as well which I guess I could get it to a decent state if it's wanted.

**Comment by lingeringwillx** [comment]
I stumbled upon [this](https://github.com/0xC0000054/DBPFSharp/blob/main/src/DBPFSharp/QfsCompression.cs
) today. Looks clean.

**Comment by LazyDuchess** [comment]
> I stumbled upon [this](https://github.com/0xC0000054/DBPFSharp/blob/main/src/DBPFSharp/QfsCompression.cs) today. Looks clean.

Indeed! I've implemented this library for compression and decompression and it all works great now. Thanks!
