### ISSUE TITLE
Figure out .mxf (Font) format

### ISSUE THREAD

**Issue by LazyDuchess** [LazyDuchess/OpenTS2#55]
Fonts can be found in TSData/Res/UI/Fonts. Haven't looked into these yet.

**Comment by polikarmike** [comment]
Hello, a few days ago, I wrote a Python script to extract data in this format. In general, it's just a wrapper. It's extracted into PFB (PostScript Type).

More information here:
https://www.wiki.sc4devotion.com/index.php?title=MXF

P.S. You're doing an awesome job, I constantly follow the project's development!

**Comment by LazyDuchess** [comment]
> Hello, a few days ago, I wrote a Python script to extract data in this format. In general, it's just a wrapper. It's extracted into PFB (PostScript Type).
> 
> More information here: https://www.wiki.sc4devotion.com/index.php?title=MXF
> 
> P.S. You're doing an awesome job, I constantly follow the project's development!

This is really cool, thank you! Glad you like what we're doing! :)

**Comment by LazyDuchess** [comment]
can confirm this works great
