### ISSUE TITLE
Render Game Fonts (Convert .pfb to .ttf)

### ISSUE THREAD

**Issue by LazyDuchess** [LazyDuchess/OpenTS2#56]
MXF fonts are included in the "TSData\Res\UI\Fonts" folder of the basegame and any DLC that adds new fonts.

Decoding them is pretty easy, as detailed in issue #55, these will produce a PostScript Type 1 Font file (PFB) for TS2 fonts (There might be TTF fonts too? not sure). The problem now is actually importing these fonts for use in the game.

I believe Unity allows you to create custom Font assets using bitmaps, so we'll probably have to find a way to load and render these into a Font asset. We also need to parse the FontStyles.ini file from the latest DLC also found in the Fonts folder to load the proper sizes and styles used for UI elements, this is the easy part.

**Comment by LazyDuchess** [comment]
I've made a new branch called `skia-text` that uses [SkiaSharp](https://github.com/mono/SkiaSharp) to render text, which allows us to load TrueType Fonts at runtime, decoded form the MXF files.

Problem now is that a couple of the game's fonts are in PostScript Type 1 (.pfb) format, which Skia doesn't parse. Have to find a way to convert these into .ttf files that we can use.

**Comment by lingeringwillx** [comment]
For hacky non-C# solutions: It's possible to convert the fonts using either fontforge or afdkom, by calling their commands through a system call and saving the font to a file, but both are big projects and including them requires some work. Fontforge is also GPL-licensed. You could either include a portable build of fontforge, or include afdko along with the whole python interpreter.

**Comment by LazyDuchess** [comment]
Hmm yeah I believe converting them with a separate tool at startup might be our best bet

**Comment by LazyDuchess** [comment]
Not the most elegant solution but it works! thanks a mil for the contributions. Maybe later down the line, if we really want to we can do something less hacky.

![image](https://github.com/LazyDuchess/OpenTS2/assets/42678262/7f3d2aa7-64c1-44b7-9528-f0916b89e6e2)
