### ISSUE TITLE
A revamped version

### ISSUE THREAD

**Issue by yunylz** [LazyDuchess/OpenTS2#61]
I am aware that this project isn't finished and there's so many things to work on but I feel like this project could be something where the game is remade in HD with new and better graphics since Unity can handle it well? Instead of just copying the game straight to Unity, a revamped version could be nicer.

**Comment by LazyDuchess** [comment]
Hey! We're trying to keep the project as legal as possible copyright wise, so remaking/revamping assets as opposed to loading them from your local installation is a no go for us. This kind of thing is better left to modders, though I'm open to working on nicer shaders and graphical effects as optional settings for sure.
